---
- name: build app
  hosts: build
  become: yes

  tasks:
  - name: Ensure clone project from git
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /usr/local

  - name: Ensure maven is present
    apt:
     name: maven
     state: present

  - name: Ensure maven build project
    shell: mvn package -f "/home/admin_vm11/boxfuse-sample-java-war-hello/pom.xml"

  - name: Copy war file from build host to local
    fetch: src=/usr/local/boxfuse-sample-java-war-hello/target/hello-1.0.war dest=/home/admin_vm10/boxfuse-sample-java-war-hello/target/hello-1.0.war

- name: web
  hosts: web
  become: yes

  tasks:
   - name: Copy war file from local to web host
     copy: src=/home/admin_vm10/boxfuse-sample-java-war-hello/target/hello-1.0.war dest=/usr/local/boxfuse-sample-java-war-hello/target/hello-1.0.war

   - name: Ensure tomcat is present
     apt:
      name: tomcat9
      state: present

   - name: Copy war file from local to webaaps
     copy: src=/usr/local/boxfuse-sample-java-war-hello/target/hello-1.0.war dest=/usr/local/tomcat/webapps/hello-1.0.war

   - name: Ensure tomcat service is started
     service:
      name: tomcat9
      state: started