---
- name: build app
  hosts: build
  become: yes

  tasks:
  - name: Ensure clone project from git
    git:
     repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
     dest: /home/admin_vm11/boxfuse-sample-java-war-hello

  - name: Ensure maven is present
    apt:
     name: maven
     state: present

  - name: Ensure maven build project
    shell: mvn package -f '/home/admin_vm11/boxfuse-sample-java-war-hello/pom.xml'

- name: web
  hosts: web
  become: yes

  tasks:
   - name: Ensure tomcat is present
     apt:
      name: tomcat9
      state: present

   - name: Copy war file from local to web host
     synchronize:
      src: rsync://root@build:/home/admin_vm11/boxfuse-sample-java-war-hello/target
      dest: /var/lib/tomcat9/webapps
     delegate_to: build


   - name: Ensure tomcat service is started
     service:
      name: tomcat9
      state: restarted